<?php

        // This doesn't have a default value, is a radio button,
        // so sometimes comes across unset
        if(! isset($FinAid)) {
            $FinAid = '';
        }
        error_reporting(E_ALL ^ E_NOTICE); // Suppress notices when exporting old apps
		echo (isset($ddlPrefix)?$ddlPrefix.',':','); 
		     echo (isset($txtLName)?$txtLName.',':',');
		     echo (isset($txtFName)?$txtFName.',':',');
		     echo (isset($txtMiddleName)?$txtMiddleName.',':',');
		     echo (isset($txtSuffix)?$txtSuffix.',':',');
			 echo (isset($txtPreferred)?$txtPreferred.',':',');
			 echo (isset($txtMaiden)?$txtMaiden.',':',');
			 echo (isset($radGender)?$radGender.',':',');
			 echo (isset($txtSSN)?$txtSSN.',':',');
			 echo (isset($txtDOB)?$txtDOB.',':',');
			 echo (isset($txtPermAdd)?$txtPermAdd.',':',');
			 echo (isset($txtPermAdd2)?$txtPermAdd2.',':',');
			 echo (isset($txtPermCity)?$txtPermCity.',':',');
			 echo (isset($ddlpermstate)?$ddlpermstate.',':',');
			 echo (isset($txtPermZip)?$txtPermZip.',':',');
			 echo (isset($ddlCountry)?$ddlCountry.',':',');
			 echo (isset($txtPhone)?$txtPhone.',':',');
			 echo (isset($txtPhoneCell)?$txtPhoneCell.',':',');
             echo ''/* fax */.',';
			 echo (isset($txtEmailWork)?$txtEmailWork.',':',');
			 echo (isset($txtEmailPer)?$txtEmailPer.',':',');
			 echo (isset($txtEmp)?$txtEmp.',':',');
			 echo (isset($txtEmpAdd)?$txtEmpAdd.',':',');
			 echo (isset($txtEmpCity)?$txtEmpCity.',':',');
			 echo (isset($ddlempstate)?$ddlempstate.',':',');
			 echo (isset($txtEmpZip)?$txtEmpZip.',':',');
			 echo (isset($txtWorkPhone)?$txtWorkPhone.',':',');
			 echo ''/* parent1 relation*/.',';
			 echo ''/* parent1 lastname*/.',';
			 echo ''/* parent1 firstname */.',';
			 echo ''/* parent1 street1 */.',';
			 echo ''/* parent1 street2 */.',';
			 echo ''/* parent1 city */.',';
			 echo ''/* parent1 state */.',';
			 echo ''/* parent1 zip */.',';
			 echo ''/* parent1 phone*/.',';
			 echo ''/* parent1 email */.',';
			 echo ''/* parent2 relation */.',';
			 echo ''/* parent2 lastname*/.',';
			 echo ''/* parent2 firstname */.',';
			 echo ''/* temp address 1 */.',';
			 echo ''/* temp address2 */.',';
			 echo ''/* temp city */.',';
			 echo ''/* temp state */.',';
			 echo ''/* temp zip */.',';
			 echo ''/* temp phone? */.',';
			 echo (isset($ddlCitizen)?$ddlCitizen.',':',');
			 echo (isset($txtImmigration)?$txtImmigration.',':',');
			 echo (isset($ddlCOB)?$ddlCOB.',':',');
			 echo ''/* test high school */.',';
			 echo ''/* high school city */.',';
			 echo ''/* high school state */.',';
			 echo ''/* GED */.',';
			 echo ''/* GradDate */.',';
			 echo ''/* rank */.',';
			 echo ''/* high school gpa */.',';
			 echo ''/* ACT1 */.',';
			 echo ''/* ACT2 */.',';
			 echo ''/* ACT3 */.',';
			 echo ''/* ACT4 */.',';
			 echo ''/* ACT Comp */.',';
			 echo ''/* SAT Math */.',';
			 echo ''/* SAT Verbal */.',';
			 echo (isset($txtPriorCollege1)?$txtPriorCollege1.',':',');
			 echo (isset($txtCollegeCity1)?$txtCollegeCity1.',':',');
			 echo (isset($ddlCollegeState1)?$ddlCollegeState1.',':',');
			 echo (isset($txtPriorCollege2)?$txtPriorCollege2.',':',');
			 echo (isset($txtCollegeCity2)?$txtCollegeCity2.',':',');
			 echo (isset($ddlCollegeState2)?$ddlCollegeState2.',':',');
			 echo (isset($txtPriorCollege3)?$txtPriorCollege3.',':',');
			 echo (isset($txtCollegeCity3)?$txtCollegeCity3.',':',');
			 echo (isset($ddlCollegeState3)?$ddlCollegeState3.',':',');
			 echo (isset($txtPriorCollege4)?$txtPriorCollege4.',':',');
			 echo (isset($txtCollegeCity4)?$txtCollegeCity4.',':',');
			 echo (isset($ddlCollegeState4)?$ddlCollegeState4.',':',');
			 echo (isset($txtPriorCollege5)?$txtPriorCollege5.',':',');
			 echo (isset($txtCollegeCity5)?$txtCollegeCity5.',':',');
			 echo (isset($ddlCollegeState5)?$ddlCollegeState5.',':',');
			 echo (isset($radmilitary)?$radmilitary.',':',');
			 echo ''/* Previously Attended Concordia */.',';
			 echo ''/* Siblings */.',';
			 echo ''/* Legacy */.',';
			 echo (isset($txtCong)?$txtCong.',':',');
			 echo (isset($txtCongStreet)?$txtCongStreet.',':',');
			 echo (isset($txtCongCity)?$txtCongCity.',':',');
			 echo (isset($ddlCongState)?$ddlCongState.',':',');
			 echo (isset($ddlAffiliation)?$ddlAffiliation.',':',');
			 echo ''/* local news*/.',';
			 echo (isset($ddlTerm)?$ddlTerm.',':',');
			 echo (isset($ddlProgram)?$ddlProgram.',':',');
			 echo ''/* major 2 */.',';
			 echo ''/* minor */.',';
			 echo (isset($Concentration)?$Concentration.',':',');
			 echo (isset($StuType)?$StuType.',':',');
			 echo (isset($RecruitType)?$RecruitType.',':',');
			 echo (isset($College)?$College.',':',');
			 echo (isset($Degree)?$Degree.',':',');
			 echo (isset($Level)?$Level.',':',');
			 echo (isset($Interest1)?$Interest1.',':',');
			 echo ''/* interest 2 */.',';
			 echo ''/* interest 3 */.',';
			 echo ''/* cohort */.',';
			 echo (isset($Recruiter)?$Recruiter.',':',');
			 echo ''/*commplan*/.',';
			 echo (isset($waiverCode)?$waiverCode.',':',');
			 echo ''/* ethnicity */.',';
			 echo (isset($JobTitle)?$JobTitle.',':',');
			 echo ''/* username */.',';
			 echo (isset($FinAid)?$FinAid.',':',');
			 echo ''/* contact code */.',';
			 echo ''/* GMATDate */.',';
			 echo ''/* GMATScore */.',';
			 echo ''/* GMATSent */.',';
			 echo ''/* FA Release */.',';
			 echo ''/* rad fin aid res */.',';
			 echo ''/* rad high school grad */.',';
			 //echo (isset($radFinancial-Aid_Residency)?$.',':',');
			 //echo (isset($radHigh-School_Graduate)?$.',':',');
			 echo (isset($Reimburse)?$Reimburse.',':',');
			 echo ''/* employer reimbursement-term */.',';
			 echo ''/* employer reimbursement-annual */.',';
			 echo (isset($ddlHear)?$ddlHear.',':',');
			 echo ''/* promo code */.',';
			 echo (isset($radFelony)?$radFelony.',':',');
			 echo (isset($txtFelony_Explain)?$txtFelony_Explain.',':',');
			 echo ''/* text message */.',';
			 echo ''/* college readiness program */.',';
			 echo ''/* parent2 street1*/.',';
			 echo ''/* parent2 street2 */.',';
			 echo ''/* parent2 city */.',';
			 echo ''/* parent2 state */.',';
			 echo ''/* parent2 zip */.',';
			 echo ''/* parent2 phone */.',';
			 echo (isset($ddlLocation)?$ddlLocation.',':','); // Loca_burnsville -Export Location here.
			 echo ''/* Church Work attribute */.',';
			 echo ''/* SATW1 */.',';
			 echo ''/* interest 4 */.',';
			 echo ''/* campus */.',';
			 echo ''/* parent1 employer */.',';
			 echo ''/* parent1 title */.',';
			 echo ''/* parent 1 contact */.',';
			 echo ''/* parent2 employer */.',';
			 echo ''/* parent2 title */.',';
			 echo ''/* parent2 contact */.',';
			 echo ''/* parent2 email */.',';
			 echo ''/* hispanic */.',';
			 echo ''/* am indian */.',';
			 echo ''/* asian */.',';
			 echo ''/* black */.',';
			 echo ''/* hawaiian */.',';
			 echo ''/* white */.',';
			 echo ''/* prefer not to respond */.',';
			 echo ''/* first generation */.',';
			 echo (isset($radGi)?$radGi.',':',');
			 echo (isset($corp_partner)?$corp_partner.',':',');
			 echo ''/* phi theta kappa */.',';
			 echo ''/* former name */.',';
			 echo ''/* teaching cert */.',';
			 echo (isset($radServingMilitary)?$radServingMilitary.',':',');
			 echo ''/* home school */.',';
			 echo ''/* division 2 */.',';
			 echo ''/* DII sport interest code */."\n";
?>
