<?php
  echo
      $prefix.'|'.
      $first_name.'|'.
      $middle_name.'|'.
      $last_name.'|'.
      $suffix.'|'.
      $other_name.'|'.
      $social_tax_id.'|'.
      $dob.'|'.
      $email.'|'.
      $home_phone.'|'.
      $cell_phone.'|'.
      $gender.'|'.
      $marital_status.'|'.
      $country_citizen.'|'.
      $citizen.'|'.
      $green_card.'|'.
      $green_card_number.'|'.
      $greencard_expires.'|'.
      $veteran.'|'.
      $military_branch.'|'.
      $address1.'|'.
      $address2.'|'.
      $city.'|'.
      $state.'|'.
      $zip_code.'|'.
      $county_ohio.'|'.
      $country.'|'.
      $hispanic_latino.'|'.
      $raceSelect.'|'.
      $racial_identity.'|'.
      $religous_preference.'|'.
      $cpid.'|'.
      $attending.'|'.
      $preferred_contact.'|'.
      $start_term.'|'.
      $enrollment_year.'|'.
      $current_employer.'|'.
      $current_employer_addr1.'|'.
      $current_employer_addr2.'|'.
      $current_employer_city.'|'.
      $current_employer_state.'|'.
      $current_employer_zip.'|'.
      $current_employer_country.'|'.
      $current_employer_phone.'|'.
      $current_employer_ext.'|'.
      $current_employer_reimburse.'|'.
      $high_school_name.'|'.
      $high_school_ceeb.'|'.
      $high_school_addr1.'|'.
      $high_school_addr2.'|'.
      $high_school_city.'|'.
      $high_school_state.'|'.
      $high_school_zip.'|'.
      $high_school_country.'|'.
      $high_school_phone.'|'.
      $high_school_graduation.'|'.
      $high_school_counselor.'|'.
      $high_school_college_credit.'|'.
      $txtPriorCollege1.'|'.
      $ceeb1.'|'.
      $txtPriorCollege2.'|'.
      $ceeb2.'|'.
      $txtPriorCollege3.'|'.
      $ceeb3.'|'.
      $txtPriorCollege4.'|'.
      $ceeb4.'|'.
      $txtPriorCollege5.'|'.
      $ceeb5.'|'.
      $personal_statement."\r\n";
?>

