GRANT ALL PRIVILEGES ON *.* TO 'dev_admin'@'127.0.0.1' IDENTIFIED BY 'R3volution!' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'dev_admin'@'localhost' IDENTIFIED BY 'R3volution!' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'dev_admin'@'%' IDENTIFIED BY 'R3volution!' WITH GRANT OPTION;